name: Terraform  

on:  
  workflow_dispatch:  # Trigger this manually or based on your needs  

jobs:  
  terraform:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  

      - name: Set up Terraform  
        uses: hashicorp/setup-terraform@v1  
        with:  
          terraform_version: 1.1.0  # Specify the Terraform version  

      - name: Terraform Init  
        run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"  

      - name: Terraform Destroy  
        run: terraform destroy -auto-approve  
        env:  
          # Set required environment variables  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}